### PR TITLE
Docker builds

### LINKED ISSUE #63: Request for docker image
Hi,

I see, there's great support for Windows, and even binary .exe is provided on the releases page. But Linux support is limited to build instructions that require installation of CUDA SDK on build machine and knowledge of some CUDA programming basics (#37, #62).

Therefore, it would be nice to have a docker image (or at least instructions on how to create one). I'd say, different versions of `ccap` could become different tags on docker hub.

Besides, similar projects have docker images already:
 - https://hub.docker.com/r/cbeams/vanitygen
 - https://hub.docker.com/r/mpenagar/vanitygen-plus

### PR DESCRIPTION
**Pull request by ratijas**
Hi,

I was asking for docker image, and I ended up spending a day doing it on my own. It was generally a positive deployment experience, I sure learned a thing or two in the process, and I hope it would come up handy for some.

Here is a link to Docker Hub: https://hub.docker.com/r/ratijas/vanitysearch.

### Regarding this PR

I'm not certain I've done things in the best way possible, but at least I tried doing it by books.

I wasn't able to run GPU version other than my native CCAP `5.2`: `2.0` is too old, and `6.0` is not supported by my hardware. But is compiles and executes (as far as giving help or an error message) just fine, so should work. Just for the hell of it, I also built `5.0`, and it worked as smooth as `5.2`. I'd be glad to hear feedback from someone for whom it works on older/newer hardware.

Not sure whether we need those aliased tags, e.g. `cuda-ccap-5` ➡ `cuda-ccap-5.2`. Does it make any sense, since it is not a software versioning and can't be just "updated"?

The `latest` tag probably not very useful either. But I kept it for the sake of conforming with docker hub conventions.

As stated is the commit message, CI and automated builds are not implemented. This is because I lack experience in this field. Suggestions and pull requests and more than welcome.

To be merged after #64 and #65.
Resolves #63.

### CODE REVIEW

**Comment by ratijas** [comment]
Anyone? Maintainers? @JeanLucPons 

Bump.

**Comment by JeanLucPons** [comment]
Hi,
Sorry i have no time at the moment to work on this project.
I'll have a look to this ASAP.
Thanks

**Comment by ratijas** [comment]
Good news from docker community.  Device requests were added to docker-py (https://github.com/docker/docker-py/pull/2471), so just in few weeks we can expect docker-compose to support `--gpu` switch.

**Comment by JeanLucPons** [comment]
Great 👍

**Pull request merged**
